# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151128133845 on 2015-11-30 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20151130_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_textssssss',
            new_name='question_text',
        ),
    ]
